export const UserData = [
  {
    id: 1,
    profilePicture: "orprofile.webp",
    username: "Tiya Sajal",
  },
  {
    id: 2,
    profilePicture: "orprofile.webp",
    username: "Ayesha Khan",
  },
  {
    id: 3,
    profilePicture: "orprofile.webp",
    username: "Sayesha Khan",
  },
  {
    id: 4,
    profilePicture: "orprofile.webp",
    username: "Sanaya Khan",
  },
  {
    id: 5,
    profilePicture: "orprofile.webp",
    username: "Fiza Khan",
  },
  {
    id: 6,
    profilePicture: "orprofile.webp",
    username: "Saniya Khan",
  },
  {
    id: 7,
    profilePicture: "orprofile.webp",
    username: "Prachi Agrawal",
  },
  {
    id: 8,
    profilePicture: "orprofile.webp",

    username: "Esha Mittal",
  },
  {
    id: 9,
    profilePicture: "tech Women.png",
    username: "Sajal Sao",
  },
  {
    id: 10,
    profilePicture: "orprofile.webp",
    username: "Deepika Singh",
  },
];
export const PostData = [
  {
    id: 1,
    desc: "Spread Motivation",
    photo: "orprofile.webp",
    date: "3 mins ago",
    userId: 1,
    likes: 43,
    comment: 5,
  },
  {
    id: 2,
    desc: "Spread Motivation",
    photo: "orprofile.webp",
    date: "31 mins ago",
    userId: 2,
    likes: 43,
    comment: 5,
  },
  {
    id: 3,
    desc: "Spread Love",
    photo: "orprofile.webp",
    date: "3 mins ago",
    userId: 3,
    likes: 43,
    comment: 5,
  },
  {
    id: 4,
    desc: "Spread Motivation",
    photo: "orprofile.webp",
    date: "2 hrs ago",
    userId: 4,
    likes: 43,
    comment: 5,
  },
  {
    id: 5,
    desc: "Love to see",
    photo: "orprofile.webp",
    date: "3 mins ago",
    userId: 5,
    likes: 43,
    comment: 5,
  },
  {
    id: 6,
    desc: "Spread Motivation",
    photo: "orprofile.webp",
    date: "3 mins ago",
    userId: 6,
    likes: 43,
    comment: 5,
  },
  {
    id: 7,
    desc: "Spread Motivation",
    photo: "orprofile.webp",
    date: "3 mins ago",
    userId: 7,
    likes: 43,
    comment: 5,
  },
  {
    id: 8,
    date: "3 mins ago",
    desc: "Spread Motivation",
    photo: "orprofile.webp",
    userId: 8,
    likes: 43,
    comment: 5,
  },
  {
    id: 9,
    desc: "Spread Motivation",
    photo: "orprofile.webp",
    date: "3 mins ago",
    userId: 9,
    likes: 43,
    comment: 5,
  },
  {
    id: 10,
    desc: "Spread Motivation",
    photo: "orprofile.webp",
    date: "3 mins ago",
    userId: 10,
    likes: 43,
    comment: 5,
  },
];
